/**
 * @author Mr Dk.
 * @version 2020/12/18
 */

/*
    You are given two strings s and t.

    String t is generated by random shuffling string s and then add one
    more letter at a random position.

    Return the letter that was added to t.

    Example 1:
        Input: s = "abcd", t = "abcde"
        Output: "e"
        Explanation: 'e' is the letter that was added.

    Example 2:
        Input: s = "", t = "y"
        Output: "y"

    Example 3:
        Input: s = "a", t = "aa"
        Output: "a"

    Example 4:
        Input: s = "ae", t = "aea"
        Output: "a"

    Constraints:
        0 <= s.length <= 1000
        t.length == s.length + 1
        s and t consist of lower-case English letters.

    来源：力扣（LeetCode）
    链接：https://leetcode-cn.com/problems/find-the-difference
    著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。
 */

/*
    用字母桶来实现。
 */

#include <iostream>
#include <string>
using std::cout;
using std::endl;
using std::string;

class Solution {
public:
    char findTheDifference(string s, string t) {
        int bucket[26] = { 0 };

        for (size_t i = 0; i < s.length(); i++) {
            bucket[s[i] - 'a']++;
        }

        for (size_t i = 0; i < t.length(); i++) {
            if (!bucket[t[i] - 'a']) {
                return t[i];
            }
            bucket[t[i] - 'a']--;
        }

        return 'a';
    }
};

int main()
{
    Solution s;
    
    cout << s.findTheDifference("abcd", "abcde") << endl;
    cout << s.findTheDifference("", "y") << endl;
    cout << s.findTheDifference("a", "aa") << endl;
    cout << s.findTheDifference("ae", "aea") << endl;

    return 0;
}
